### ISSUE TITLE
SRTP support and 'transcoding' between encrypted and unencrypted streams

### ISSUE THREAD

**Issue by m-pen-resilientplc** [sippy/rtpproxy#150]
Hi,

Does rtpproxy support encrypted media streams using SRTP? Are there any documention/examples of how to enable/support this?

If so, does it also support 'transcoding' between encrypted and unencrypted media streams?

Thank you.

**Comment by sobomax** [comment]
Hi, yes, it does, since version 3.0. See `modules/dtls_gw/README.md` for details, also it's used in this project for example:  [WebRTC Phone](https://github.com/sippy/webrtc_phone)

**Comment by josh4trunks** [comment]
Sorry if this isn't the best place to ask for direction; please correct me if there is a better place to ask.

I run FreeBSD, and have Kamailio controlling RTPProxy with the rtpproxy module. My understanding is the module currently has no built-in encryption support, unlike the rtpproxy-ng module which includes an 's/S' flag to enable/disable encryption. I am still somewhat new to SIP(s)/(s)RTP and learning as I go. My goal is to have SRTP between my endpoints and RTPProxy, which then forwards RTP to my Asterisk PBX.

* Is DTLS the recommended protocol over SDES? I am thinking it would be preferred since the SIP proxy (Kamailio) will not need to worry about passing keys to RTPProxy. But, I could be not understanding SIP/RTP correctly.
* Assuming I require DTLS on my Linphone clients, does RTPProxy need a valid certificate? Or are self-signed, certificates automatically generated?
* I think my best path forward at the moment is to have Kamailio modify the SDP parameters using the SDPOPS module. Replace **UDP/TLS/RTP/SAVP** with **RTP/AVP** for incoming INVITEs, and the opposite for outgoing INVITEs.

Thank you!

**Comment by josh4trunks** [comment]
After reading on DTLS at link below, it seems that it will require interaction between SIP and RTPProxy to pass along the fingerprint.
https://docs.oracle.com/en/industries/communications/session-border-controller/9.3.0/configuration/example-dtls-srtp-flows.html

So, I guess making changes to SIP flow alone using SDPOPS is not enough. We need RTPProxy module to use `dtls_gw` command to get fingerprint.

**Comment by josh4trunks** [comment]
@sobomax 
I assume to use RTPProxy encryption/decryption, with Kamailio or OpenSIPS, we will need their rtpproxy modules updated?

**Comment by josh4trunks** [comment]
@sobomax 
Sorry to bother you more, would you ever plan on updating the rtpproxy module for Kamailio or OpenSIPS?

I will eventually try to fumble through the code and add DTLS or SDES support to the module for Kamailio, but I'm sure it will take me a long time because I have minimal programming experience.

Thanks!
