### ISSUE TITLE
How to work extractaudio

### ISSUE THREAD

**Issue by xo-ua** [sippy/rtpproxy#52]
Hello,

Do you have any examples for how to run extractaudio ?
I have tried any combination but didn't get any output file.
 /usr/src/rtpproxy/extractaudio/extractaudio ?
usage: extractaudio [-idsn] [-F file_fmt] [-D data_fmt] rdir outfile [link1] ... [linkN]
e.g:
 /usr/src/rtpproxy/extractaudio/extractaudio -F wav /tmp/rtp/3HQ_lYL8EqHRda3dDnplDg..-0\=efe5cbf28320cd17db01e1c280300850.a.rtp   1.wav
but when I give a.rtp file, there is no output.
Thank you for your help.

**Comment by Homer-Rivera** [comment]
This worked for me....
Use the file name but leave off the extensions so you are only using the base filename.  Then define the second file as your output file with the wav extension.  That will generate your wave file.

extractaudio /tmp/rtp/3HQ_lYL8EqHRda3dDnplDg..-0=efe5cbf28320cd17db01e1c280300850 myfile.wav

**Comment by xo-ua** [comment]
Hi Homer-River,

Yes, your are right, thanks, but it still doesn't work for g729, output files 60 bytes 
Maybe, you use it for g723 ?
thank in advance

**Comment by sobomax** [comment]
Make sure you compile it with g729 support. It needs libbcg729 to work
properly. Thanks.

-Max


On Mar 2, 2017 10:43 AM, "xo-ua" <notifications@github.com> wrote:

Hi Homer-River,

Yes, your are right, thanks, but it still doesn't work for g729, output
files 60 bytes
Maybe, you use it for g723 ?
thank in advance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sippy/rtpproxy/issues/52#issuecomment-283741556>, or mute
the thread

**Comment by ly0** [comment]
@sobomax which libbcg729? I google it and got multiple results, seems neither of them is rtpproxy needed.

**Comment by xo-ua** [comment]
@ly0 , I used this one and it works:
git clone git://git.linphone.org/bcg729.git
--

**Comment by ly0** [comment]
@xo-ua thanks, it works. but I modified g729_compat.h/g729_compat.c/makeann.c to get it through :-(
