### ISSUE TITLE
Wont build because of libelperiodic

### ISSUE THREAD

**Issue by dovi5988** [sippy/rtpproxy#71]
This is probably more of a ID10T error then a bug..... When trying to build rtpproxy I get:
=== configuring in libelperiodic (/usr/src/rtpproxy/libelperiodic)
configure: WARNING: no configuration information is in libelperiodic

however libelperiodic is installed.
[root@bounce rtpproxy]# find / -name 'libelperiodic.so' | grep '/lib/'
/usr/lib/libelperiodic.so
/usr/local/lib/libelperiodic.so
[root@bounce rtpproxy]#

**Comment by razvancrainea** [comment]
If you are checking out `rtpproxy` from git, make sure you bring its git submodules:

```
git -C rtpproxy submodule update --init --recursive
```
This will checkout the [`libelperiodic`](https://github.com/sippy/rtpproxy/blob/master/.gitmodules) submodule in your sources and you will be able to proceed with the compilation.

**Comment by dovi5988** [comment]
Razvan - Perhaps that can be put into the README?

**Comment by sobomax** [comment]
Ok, I'll check README. Thanks for suggestion!

-Max

On Oct 4, 2017 9:29 AM, "dovi5988" <notifications@github.com> wrote:

Razvan - Perhaps that can be put into the README?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sippy/rtpproxy/issues/71#issuecomment-334213100>, or mute
the thread

**Comment by razvancrainea** [comment]
It already is [there](https://github.com/sippy/rtpproxy#building-from-github), that's where I got the command to run.

**Comment by sobomax** [comment]
Should be resolved now.
