### ISSUE TITLE
RTPProxy cant process more than 250 simultaneous calls

### ISSUE THREAD

**Issue by ShadoWalkeR31** [sippy/rtpproxy#75]
We use rtpproxy for simple NAT RTP transit between networks and encouter that rtpproxy, when reach ~250 calls start return port 0 to kamailio.
Port range for rtpproxy 20000-60000. Its not system or kamailio problem - test servers (Debian and Centos) with calls, generated by sipp shows same behavior. If i replace rtpproxy with rtpengine with same env and configs on test servers, it can process more then 1,2k simultaneous calls
I test it with packages from repos on Debian and Centos
rtpproxy-1.2.1-2.2
rtpproxy-2.0.0-6

**Comment by razvancrainea** [comment]
In my experience, this is related to the number of file descriptors limits. By default, rtpproxy uses a limit of 1024 file descriptors - every call uses about 4 descriptors, resulting in a roughly 250 concurrent calls with the default configuration.
You can try to increase this limit (by specifying a `-L` parameter at startup, e.g. `-L 8192`) and check if you see the same behavior.

**Comment by ShadoWalkeR31** [comment]
I try to increase to various numbers already - rtpproxy still fails at ~250 simultaneous calls. I think it maybe somewhere in code limitation - because its very close to 255.

**Comment by razvancrainea** [comment]
I am pretty sure this is not a code limitation, I've run rtpproxy instances with more than 1000 simultaneous sessions.
Did you try to check the rtpproxy logs to see what errors it is triggering?

**Comment by razvancrainea** [comment]
That's right, but did you start `rtpproxy` with a higher `-L` parameter? Because indeed, that value (that defaults to 1024) is a code limitation, and you won't be able to use more file descriptors than that limit, regardless of the `ulimit -n` value.

**Comment by ShadoWalkeR31** [comment]
Sorry for misunderstanding - i didn't notice, that rtpproxy has own limit for connections. I try to use rtpproxy with L option and increase simultaneous calls. Thank you

**Comment by razvancrainea** [comment]
No worries, let us know how your tests go.

**Comment by sobomax** [comment]
You might have a system-wide limit somewhere. In our experience, single
proxy can handle 75-100k PPS, which is 3-4 times greater than 250 calls or
even more if your traffic consists of frames bigger than 10ms.

-Max

**Comment by ShadoWalkeR31** [comment]
I test with -L 40000 (portrange 20000-60000) and found second limit - 4096, but its SystemD. When i disable work as user rtpproxy and run as root, sipp via test server kamailio+rtpproxy with cps 40 can load ~2.5k simultaneous calls (for now its asterisks openend and closed sessions at point ~1.25k calls each).

Thank you for your help and can you add to documentation that '-L' have default value?

**Comment by sobomax** [comment]
@ShadoWalkeR31 thanks for a feedback, we've added info about -L here, please check:

[https://www.rtpproxy.org/doc/master/user_manual.html#idm45783371036304]

Please note that -L 40000 is most likely an overkill. You should probably stick to 4xMax Sessions (make it 6x if you are not sure). Excessively high value might cause OS to make rtpproxy fail on startup.

**Comment by sobomax** [comment]
Known and well documented issue. The problem with trying to pull -L higher by default is that it requires elevated privileges to do so. So we have 3 options really:

1. Do nothing and rely on OS settings being reasonable. Unless instructed with -L otherwise;

2. Try to bump the limit to some arbitrary value by default and stick to an OS provided value when it fails;

3. Try to bump the limit to some arbitrary value by default and bail out when it fails.

Neither (2) nor (3) provides a better alternative in lieu of that elevated privileges requirement. We either would silently run with vastly different settings when started as root / non-root given the same config. Which is bad. Or we would not work at non-privileged user by default, unless you lower -L down below "OS approved value for non-superusers", which is bad too.
